version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kako_web
    ports:
      - "8080:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./inner-page.html:/var/www/html/inner-page.html
      - ./forms:/var/www/html/forms
      - ./assets:/var/www/html/assets
